inputs:
  to:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
    - id: format_commits
      shell: bash
      run: |
        commits=$(echo '${{ toJson(github.event.commits) }}' | jq -r '.[] | "🥷 \(.author.name)\n💬 \(.message)\n"')
        echo "$commits"
        echo "$commits" >> $GITHUB_OUTPUT

    - uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        message: |
          🎉 ${{github.repository}} deploy successful


          ${{ steps.format_commits.outputs.commit_messages }}
