inputs:
  to:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
    - id: format_commits
      shell: bash
      run: |
        commits=$(echo '${{ toJson(github.event.commits) }}' | python parse.py)
        echo "$commits"

        echo 'commit_messages<<EOF' >> $GITHUB_OUTPUT
        echo "$commits" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        message: |
          ✨ ${{github.repository}}
          🎉 Deploy Successful

          ${{ steps.format_commits.outputs.commit_messages }}
